#!/bin/bash
# Prepare safe workspace for GCE files

# Ensure our temporary loopback device and mount get cleaned up no matter how we
# exit, even if it's before the usual cleanup steps.
function cleanup_loopback_mount () {
  # Disable exit-on-error
  set +e

  if [ -n "$imagedir" ]; then
    log "Unmounting $imagedir ahead of unclean exit."
    umount $imagedir
  fi

  if [ -n "$device_path" ]; then
    log "Deleting loopback device $device_path ahead of unclean exit."
    losetup -d $device_path
  fi

  if [ -d "$workspace" ]; then
    log "$workspace still exists. Leaving alone for potential debugging."
  fi

  # Enable exit-on-error
  set -e
}
trap cleanup_loopback_mount ERR EXIT

workspace="$(mktemp -d -t build-debian-cloud.XXXXXXXXXX)"
tarballdir=$workspace
