#!/bin/bash

# Stop execution if any command fails
set -e

# Rember various paths
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ ! -d "$scriptdir/tasks" ]; then
	scriptdir='/usr/share/build-debian-cloud'
	if [ ! -d "$scriptdir/tasks" ]; then
		die "Unable to locate tasks folder."
	fi
fi
originaldir=$(pwd)

# Directory where the tarball created while bootstrapping should be put
tarballdir=$scriptdir

source $scriptdir/utils

# Tasks, packages, plugins, boot scripts
tasks=()
packages=()
exclude_packages=()
host_packages=()
plugins=()
init_scripts=()

# General options about the instance
arch='amd64'
locale='en_US'
charmap='UTF-8'
timezone='UTC'
apt_mirror='http://http.debian.net/debian'

# Hardcoded params.
# This script would explode if we had to take care of other distributions
distribution='debian'
codename='squeeze'

# Volume and image info
# Filesystem, hardcoded for now, maybe we'll add a parameter later on
filesystem='ext4'
mountoptions=
volume_size='1'
device_path=
imagedir=


# Split between platforms: ec2 and gce
platform_help="build-debian-cloud
This script creates a Debian Squeeze Image for
either Amazon Web Services or Google Compute Engine.

Valid subcommands are:
    ec2    Build an Amazon Machine Image
    gce    Build a Google Compute Engine Image
"

platform=$1

# Figure out which pvGrub kernel ID we need
case $platform in
	ec2|gce) shift ;;
	*)       printf -- "$platform_help"; exit 0  ;;
esac

source $platform

# Check if the chosen fs is on we can handle.
case $filesystem in
	xfs)  ;;
	ext2) ;;
	ext3) ;;
	ext4) ;;
	*)    die "The filesystem $filesystem was not recognized." \
	          "Valid filesystems are ext[2-4] and xfs"      ;;
esac

# Put all tasks in the tasks folder into an array. Tolerate the absence
# of some possible directories.
directories=`ls -d $scriptdir/tasks $scriptdir/tasks/$codename \
	$scriptdir/tasks/$platform $scriptdir/tasks/$platform/$codename \
	2>/dev/null || true`
tasklist=`find $directories \
	-maxdepth 1 -type f -name '[0-9][0-9]-*' \
	-printf '%p\t%f\n' | sort -k 2 | awk '{print $1}'`
tasks=()
for task in $tasklist; do
	if $(contains_basename `basename $task` tasks[@]); then
		die "The task $task has a naming conflict with an existing task." "Please rename the file."
	fi
	tasks+=($task)
done

# Invoke plugins so that they may reorder and add tasks
for plugin in "${plugins[@]}"; do
	[ -e $plugin ] || die "The plugin file $plugin does not exist."
	# Get the directory of the current plugin.
	# This way the plugins don't have to figure it out for themselves.
	plugindir=`dirname $plugin`
	source $plugin
done
unset plugindir

# Source all tasks in the right order
for task in ${tasks[*]}; do
	[ -e $task ] || die "The task $task does not exist."
	log "Run task: `basename $task`"
	taskdir=`dirname $task`
	source $task || true
done
unset taskdir
