#!/bin/bash

# Google cloud info
gcs_dest=
gce_project=

# Image details
image_name_suffix=$(date +%Y%m%d)

# List of options for gce subcommand
help="build-debian-cloud gce
This script creates a Debian Squeeze Amazon Machine Image.

Options (defaults in ${txtbld}bold${txtdef}):

${txtund}Bootstrapping${txtdef}
    --arch ARCH [i386|amd64]      Processor architecture of the image (${txtbld}${arch}${txtdef})
    --codename C [squeeze|wheezy] Debian version codename to bootstrap (${txtbld}${codename}${txtdef})
    --filesystem FS [ext2..4|xfs] Filesystem of the root volume (${txtbld}${filesystem}${txtdef})
    --volume-size SIZE            Default size of the root volume in GB (${txtbld}${volume_size}${txtdef})
    --plugin FILE                 Path to plugin script.
                                  Can be specified more than once.

    --timezone ZONE               Standard timezone (${txtbld}${timezone}${txtdef})
    --locale LOCALE               Standard locale (${txtbld}${locale}${txtdef})
    --charmap CHARMAP             Standard charmap (${txtbld}${charmap}${txtdef})

    --name SUFFIX                 Image name suffix (${txtbld}${name_suffix}${txtdef})

${txtund}GCE${txtdef}
    --gcs-dest URL                Google Cloud Storage image destination URL (${txtbld}${gcs_dest}${txtdef})
    --gce-project PROJECT         Google Compute Engine image destination project (${txtbld}${gce_project}${txtdef})

${txtund}Other options${txtdef}
    --debug                       Print debugging information
    --help                        Prints this help message
"

# Run through the parameters and save them to variables.
while [ $# -gt 0 ]; do
	case $1 in
		--arch)             arch=$2;                       shift 2 ;;
		--codename)         codename=$2;                   shift 2 ;;
		--filesystem)       filesystem=$2;                 shift 2 ;;
		--volume-size)      volume_size=$2;                shift 2 ;;
		--name)             name_suffix=$2;                shift 2 ;;
		--gcs-dest)         gcs_dest=$2;                   shift 2 ;;
		--gce-project)      gce_project=$2;                shift 2 ;;
		--timezone)         timezone=$2;                   shift 2 ;;
		--locale)           locale=$2;                     shift 2 ;;
		--charmap)          charmap=$2;                    shift 2 ;;
		--plugin)           plugins+=("$2");               shift 2 ;;
		--debug)            set -x;                        shift   ;;
		-h|--help)          printf -- "$help";             exit 0  ;;
		*)             die "Unrecognized option: $1" \
    "Type '$0 --help' to see a list of possible options"; ;;
	esac
done


# Specify points in the bootstrapping process, which the plugins can latch onto.
# This way plugins don't need fixing if we rename files.
TASK_CREATE_VOLUME="10-create-volume"
TASK_MOUNT_VOLUME="13-mount-volume"
TASK_DELETE_VOLUME="73-delete-loopback"
TASK_REGISTER_IMAGE="95-register-image"
