#!/bin/bash
instance_information=`curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document`
instance_id=`echo "$instance_information" | grep instanceId | awk -F\" '{print $4}'`
region=`echo "$instance_information" | grep region | awk -F\" '{print $4}'`
availability_zone=`echo "$instance_information" | grep availabilityZone | awk -F\" '{print $4}'`

if [ -z "$instance_id" ]; then
	die \
		"Unable to fetch the instance id of this machine." \
		"This script must be running on ec2 in order to mount EBS volumes."
fi
[ -z "$region" ] && die "Unable to fetch the region of this machine."
[ -z "$availability_zone" ] && die "Unable to fetch the availability zone of this machine."

if [ -z "$EC2_URL" ]; then
	export EC2_URL="https://$region.ec2.amazonaws.com"
fi

case $region in
	eu-west-1)      bootstrap_mirror="http://ftp.ie.debian.org/debian" ;;
	us-east-1)      bootstrap_mirror="http://ftp.us.debian.org/debian" ;;
	us-west-1)      bootstrap_mirror="http://ftp.us.debian.org/debian" ;;
	us-west-2)      bootstrap_mirror="http://ftp.us.debian.org/debian" ;;
	ap-northeast-1) bootstrap_mirror="http://ftp.jp.debian.org/debian" ;;
	ap-southeast-1) bootstrap_mirror="http://mirror.nus.edu.sg/Debian/" ;;
	sa-east-1)      bootstrap_mirror="http://ftp.br.debian.org/debian" ;;
	*)              die "$0: Unrecognized region: $region"
esac
