#!/bin/bash
# Add some standard packages we are going to need
packages+=('grub')
packages+=('locales')
packages+=('openssh-server')
packages+=('curl')
packages+=('less')
packages+=('udev')
packages+=('psmisc')
packages+=('lsb-release')
packages+=('dhcpcd')
packages+=('file')
[ $arch = 'i386' ] && packages+=('linux-image-xen-686')
[ $arch = 'amd64' ] && packages+=('linux-image-xen-amd64')

exclude_packages+=('isc-dhcp-client')
exclude_packages+=('isc-dhcp-common')
