#!/bin/bash
# Add some basic packages we are going to need
packages+=('grub')
packages+=('udev')
packages+=('openssh-server')
# We could bootstrap without locales, but things just suck without them,
# error messages etc.
packages+=('locales')
# Needed for the init scripts
packages+=('file')
# This is inherited from the original script.
# Apparently isc-dhcp-client doesn't work properly with ec2
packages+=('dhcpcd')

[ $arch = 'i386' ] && packages+=('linux-image-xen-686')
[ $arch = 'amd64' ] && packages+=('linux-image-xen-amd64')

# We use dhcpcd instead
exclude_packages+=('isc-dhcp-client')
exclude_packages+=('isc-dhcp-common')

# euca2ools dependencies
host_packages+=('build-essential')
host_packages+=('python-boto')
host_packages+=('python-m2crypto')

# We will need to format the volume, so we need xfsprogs
[ $filesystem = 'xfs' ] && host_packages+=('xfsprogs')
# In order to make sure a volume is not busy, before unmounting we need lsof
host_packages+=('lsof')
host_packages+=('debootstrap')
