#!/bin/bash
# Add some standard packages we are going to need
packages+=('grub' 'locales' 'openssh-server' 'curl')
packages+=('less' 'udev' 'psmisc' 'lsb-release' 'dhcpcd')
[ $arch = 'i386' ] && packages+=('linux-image-xen-686')
[ $arch = 'amd64' ] && packages+=('linux-image-xen-amd64')

exclude_packages=('isc-dhcp-client' 'isc-dhcp-common')
