#!/bin/bash
# Install packages on the host system to make the rest of this script run smoothly

apt-get install -y ${host_packages[*]} | spin
[ $PIPESTATUS == 0 ] || die "Installing host packages failed!"

# We use euca2ools to communicate with AWS
# The package in squeeze is v 1.2, which does not support EBS images
# So we install 1.3 from source instead
if [ ! -d $scriptdir/euca2ools ]; then
	wget -qO $scriptdir/euca2ools-1.3.2.tar.gz https://github.com/eucalyptus/euca2ools/archive/1.3.2.tar.gz
	tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
fi

function install_euca2ools {
	# We want to fail if make fails, so don't start a subshell with ()
	# Remember the old dir
	local orig_pwd=$(pwd)
	cd euca2ools-1.3.2
	make | spin
	[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
	cd $orig_pwd
}

# make the euca2ools if they are not installed or the version is wrong
if ! command -v euca-version > /dev/null 2>&1; then
	install_euca2ools
elif [[ ! "`euca-version`" =~ euca2ools\ 1.3.* ]]; then
	install_euca2ools
fi
