#!/bin/bash
# Install packages on the host system to make the rest of this script run smoothly

apt-get install -y ${host_packages[*]} | spin
[ $PIPESTATUS == 0 ] || die "Installing host packages failed!"

# We use euca2ools to communicate with AWS
# The package in squeeze is v 1.2, which does not support EBS images
# So we install 1.3 from source instead
if [ ! -d $scriptdir/euca2ools ]; then
	curl -s -L -o $scriptdir/euca2ools-1.3.2.tar.gz https://github.com/eucalyptus/euca2ools/archive/1.3.2.tar.gz
	tar zxf $scriptdir/euca2ools-1.3.2.tar.gz
fi

# We want to fail if make fails, so don't start a subshell with ()
# Remember the old dir
pwd_before_euca_make=$(pwd)
cd euca2ools-1.3.2
make | spin
[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
cd $pwd_before_euca_make
