#!/bin/bash
# Retreive information about the host system
instance_information=`curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document`
# We need the region, for the apt sources and the availability zone for the EBS volume
instance_id=`printf -- "$instance_information" | grep instanceId | awk -F\" '{print $4}'`
region=`printf -- "$instance_information" | grep region | awk -F\" '{print $4}'`
availability_zone=`printf -- "$instance_information" | grep availabilityZone | awk -F\" '{print $4}'`

if [ -z "$instance_id" ]; then
	die \
		"Unable to fetch the instance id of this machine." \
		"This script must be running on ec2 in order to mount EBS volumes."
fi
[ -z "$region" ] && die "Unable to fetch the region of this machine."
[ -z "$availability_zone" ] && die "Unable to fetch the availability zone of this machine."

# Set the ec2_url to the same region as this machine, anything else wouldn't make sense
export EC2_URL="https://$region.ec2.amazonaws.com"

# We can speed up the bootstrapping process by choosing a debian mirror nearby
case $region in
	us-east-1)      apt_mirror="http://ftp.us.debian.org/debian/" ;;
	us-west-1)      apt_mirror="http://ftp.us.debian.org/debian/" ;;
	us-west-2)      apt_mirror="http://ftp.us.debian.org/debian/" ;;
	eu-west-1)      apt_mirror="http://ftp.ie.debian.org/debian/" ;;
	ap-southeast-1) apt_mirror="http://mirror.nus.edu.sg/Debian/" ;;
	ap-southeast-2) apt_mirror="http://ftp.au.debian.org/debian/" ;;
	ap-northeast-1) apt_mirror="http://ftp.jp.debian.org/debian/" ;;
	sa-east-1)      apt_mirror="http://ftp.br.debian.org/debian/" ;;
	us-gov-west-1)  apt_mirror="http://ftp.us.debian.org/debian/" ;;
	*)              die "Unrecognized region:" "$region"
esac
