#!/bin/bash
# boto has bug when registering images, we fix it with this
function apply_boto_patch {
	local boto_ec2_dir='/usr/share/pyshared/boto/ec2'
	local patch_url='https://bugzilla.redhat.com/attachment.cgi?id=455857'
	if [ -r "$boto_ec2_dir/blockdevicemapping.py" ]; then
		local result=$(
			grep -q "pre = '%sBlockDeviceMapping.%d' % (pre, i)" $boto_ec2_dir/blockdevicemapping.py
			echo $?)
		if [ $result -eq 0 ]; then
			wget -qO - $patch_url | patch -sfr - -d $boto_ec2_dir
			[ $PIPESTATUS == 0 ] || die "Unable to patch boto."
		fi
	fi
}
apply_boto_patch
