#!/bin/bash
# Retreive information about the host system
instance_information=`wget -qO - http://169.254.169.254/latest/dynamic/instance-identity/document`
# We need the region, for the apt sources and the availability zone for the EBS volume
instance_id=`printf -- "$instance_information" | grep instanceId | awk -F\" '{print $4}'`
region=`printf -- "$instance_information" | grep region | awk -F\" '{print $4}'`
availability_zone=`printf -- "$instance_information" | grep availabilityZone | awk -F\" '{print $4}'`

if [ -z "$instance_id" ]; then
	die \
		"Unable to fetch the instance id of this machine." \
		"This script must be running on ec2 in order to mount EBS volumes."
fi
[ -z "$region" ] && die "Unable to fetch the region of this machine."
[ -z "$availability_zone" ] && die "Unable to fetch the availability zone of this machine."

# Set the ec2_url to the same region as this machine, anything else wouldn't make sense
export EC2_URL="https://ec2.$region.amazonaws.com"

# Check if we can handle this region, there are hardcoded AKIs later on.
if ! $(contains $region known_regions[@]); then
	die "The region $region is unkown."
fi
