#!/bin/bash
[ -n "`mount | grep "$imagedir"`" ] && die "Something is already mounted on $imagedir"

device_letter=`cat /dev/urandom| tr -dc 'f-p'|head -c 1`
while [ -b "/dev/xvd$device_letter" ]; do
	device_letter=`cat /dev/urandom| tr -dc 'f-p'|head -c 1`
done
device="/dev/sd$device_letter"
device_path="/dev/xvd$device_letter"
filesystem='xfs'

[ -n "`df | grep $device_path`" ] && die "Something is already attached to $device_path."

if [ ! -d "$imagedir" ]; then
	mkdir -p $imagedir
fi

echo "Creating a volume now."
volume_id=`ec2-create-volume --size 1 \
	--region "$region" --availability-zone "$availability_zone" \
	| awk '{print $2}'`
[ -z "$volume_id" ] && die "Unable to create volume."

echo "Attaching volume with the id $volume_id"
attachment_status=`ec2-attach-volume "$volume_id" \
	--instance "$instance_id" --device "$device" | grep 'attached' || true`
while [ -z "$attachment_status" ]; do
	echo "Waiting for volume to finish attaching"
	sleep 5
	attachment_status=`ec2-describe-volumes | grep "ATTACHMENT[[:blank:]]*$volume_id.*attached" || true`
done

echo "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path
mount $device_path $imagedir
echo "The EBS volume has been formatted and mounted"

case $filesystem in
	xfs)  packages="$packages xfsprogs" ;;
	ext2) ;;
	ext3) ;;
	ext4) ;;
	*)    echo "Tools for $filesystem were not added, the corresponding package is unknown" >&2;;
esac
