#!/bin/bash
# Create the EBS volume

volume_id=`euca-create-volume --size $volume_size --zone "$availability_zone" | awk '{print $2}'`
[ -z "$volume_id" ] && die "Unable to create volume."
log "The EBS volume id is $volume_id"
