#!/bin/bash
if [ ! -d "$builddir" ]; then
	mkdir -p $builddir
	source $scriptdir/tasks/11-create-volume
elif [ -z "`mount | grep "$builddir"`" ]; then
	source $scriptdir/tasks/11-create-volume
else
	echo "Using the volume already mounted on $builddir"
	if [ -z "$volume_id" ]; then
		die \
			"You must specify the volume ID when you want to mount it yourself." \
			"Otherwise creating the snapshot later on will not be possible."
	fi
fi
imagedir=$builddir
