#!/bin/bash
device='/dev/sdf'
device_path='/dev/xvdf'
filesystem='xfs'

[ -n "`df | grep $device_path`" ] && die "Something is already attached to $device_path."

if [ -z "$volume_id" ]; then
	echo "No volume id specified, creating a volume now."
	volume_id=`ec2-create-volume --size 1 \
		--region "$region" --availability-zone "$availability_zone" \
		| awk '{print $2}'`
	[ -z "$volume_id" ] && die "Unable to create volume."
else
	echo "Checking the status of the specified volume."
	volume_status=`ec2-describe-volumes | grep "VOLUME[[:blank:]]*$volume_id.*available" || true`
	if [ -z "$volume_status" ]; then
		die \
			"Please detach the volume $volume_id. Even if it is this instance it is" \
			"attached to.
			You can of course also simply mount the volume, specify the " \
			"mountpoint and skip this procedure entirely." \
			"Otherwise detach with 'ec2-detach-volume $volume_id'."
	fi
fi

echo "Attaching volume with the id $volume_id"
attachment_status=`ec2-attach-volume "$volume_id" \
	--instance "$instance_id" --device "$device" | grep 'attached' || true`
while [ -z "$attachment_status" ]
do
	echo "Waiting for volume to finish attaching"
	sleep 5
	attachment_status=`ec2-describe-volumes | grep "ATTACHMENT[[:blank:]]*$volume_id.*attached" || true`
done

echo "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path
mount $device_path $imagedir
echo "The EBS volume has been formatted and mounted"

case $filesystem in
	xfs)  packages="$packages xfsprogs" ;;
	ext2) ;;
	ext3) ;;
	ext4) ;;
	*)    echo "Tools for $filesystem were not added, the corresponding package is unknown" >&2;;
esac
