#!/bin/bash
# Format the EBS volume

log "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path

case $filesystem in
	# Disable time based fs checks
	ext2) tune2fs -i 0 $device_path ;;
	ext3) tune2fs -i 0 $device_path ;;
	ext4) tune2fs -i 0 $device_path ;;
	# Add some tools for xfs, ext tools are built-in
	xfs)  packages+=('xfsprogs')    ;;
esac
