#!/bin/bash
# Format the volume

log "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path

case $filesystem in
	# Disable time based fs checks
	ext*) tune2fs -i 0 $device_path ;;
	# Add some tools for xfs, ext tools are built-in
	xfs)  packages+=('xfsprogs')    ;;
esac
