#!/bin/bash
# Bootstrap

# Concatenate the packages
SAVE_IFS=$IFS
IFS=","
include="${packages[*]}"
exclude="${exclude_packages[*]}"
IFS=$SAVE_IFS

bootstrap_args="--arch $arch --include=$include --exclude=$exclude
$codename $imagedir $apt_mirror"

args_hash=`printf -- "$arch $include -- $exclude $codename" | sha1sum`

tarball="$tarballdir/bootstrap-${args_hash:0:7}.tar"

include_param=""
if [[ $include != "" ]]; then
	include_param="--include=$include"
fi

exclude_param=""
if [[ $exclude != "" ]]; then
	exclude_param="--exclude=$exclude"
fi

# When testing, some bootstraps can fail, instead of re-downloading it all
# we create a tarball containing all the necessary things for bootstrapping
if [ ! -e "$tarball" ]; then
	log "Creating the bootstrap tarball"
	debootstrap --arch $arch --make-tarball=$tarball \
		${include_param} ${exclude_param} \
		$codename $imagedir $apt_mirror | spin
	[ $PIPESTATUS == 1 ] || die "Creating bootstrap tarball failed!"
fi

log "Bootstrapping"
debootstrap --arch $arch --unpack-tarball=$tarball \
	${include_param} ${exclude_param} \
	$codename $imagedir $apt_mirror | spin
[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
