#!/bin/bash
# Bootstrap

# Concatenate the packages
SAVE_IFS=$IFS
IFS=","
include="${packages[*]}"
exclude="${exclude_packages[*]}"
IFS=$SAVE_IFS

bootstrap_args="--arch $arch --include=$include --exclude=$exclude
$codename $imagedir $apt_mirror"

args_hash=`echo $bootstrap_args | sha1sum`

tarball="$scriptdir/bootstrap-${args_hash:0:7}.tar"

if [ ! -e "$tarball" ]; then
	log "Creating the bootstrap tarball"
	debootstrap --arch $arch --make-tarball=$tarball \
		--include=$include --exclude=$exclude \
		$codename $imagedir $apt_mirror | spin
	[ $PIPESTATUS == 1 ] || die "Creating bootstrap tarball failed!"
fi

log "Bootstrapping"
debootstrap --arch $arch --unpack-tarball=$tarball \
	--include=$include --exclude=$exclude \
	$codename $imagedir $apt_mirror | spin
[ $PIPESTATUS == 0 ] || die "Bootstrapping failed!"
