#!/bin/bash
# Mount special devices

# Unmount if the bootstrapping fails, but keep the trap used by Google Compute
# Engine builds.
trap "printf 'Bootstrapping failed!\n'
cd $originaldir
chroot $imagedir umount /dev/pts
chroot $imagedir umount /sys
chroot $imagedir umount /proc
umount $imagedir/dev

declare -F cleanup_loopback_mount >/dev/null 2>&1 && cleanup_loopback_mount
" ERR EXIT

# Mount all the different special devices, other installers depend on their existence
mount --bind /dev $imagedir/dev
chroot $imagedir mount -t proc none /proc
chroot $imagedir mount -t sysfs none /sys
chroot $imagedir mount -t devpts none /dev/pts
