#!/bin/bash
# Set locale
# Install the locales package
chroot $imagedir apt-get install -y --force-yes locales
# Uncomment the chosen locale
sed -i "s/# $locale.$charmap $charmap/$locale.$charmap $charmap/" $imagedir/etc/locale.gen
# Generate the locale
chroot $imagedir dpkg-reconfigure --priority=critical locales

# Set timezone
echo $timezone >$imagedir/etc/timezone
/bin/cp -f $imagedir/usr/share/zoneinfo/$timezone $imagedir/etc/localtime
