#!/bin/bash
# Basic sources.list
cat <<EOF >$imagedir/etc/apt/sources.list
deb http://security.debian.org/       $codename/updates main contrib non-free
deb-src http://security.debian.org/   $codename/updates main contrib non-free
deb $apt_mirror     $codename         main contrib non-free
deb-src $apt_mirror $codename         main contrib non-free
EOF
