#!/bin/bash
# Basic sources.list
cat > $imagedir/etc/apt/sources.list <<EOF
deb     $apt_mirror $codename         main
deb-src $apt_mirror $codename         main
deb     http://security.debian.org/   $codename/updates main
deb-src http://security.debian.org/   $codename/updates main
EOF
