#!/bin/bash
# Upgrade packages installed by debootstrap

# Don't launch daemons when upgrading
cat > $imagedir/usr/sbin/policy-rc.d << EOF
#!/bin/sh
exit 101
EOF
chmod 755 $imagedir/usr/sbin/policy-rc.d

# Update the package cache
chroot $imagedir apt-get update | spin
[ $PIPESTATUS == 0 ] || die "apt-get update failed!"

# Fix broken dependencies, if any.
chroot $imagedir apt-get -f install -y

# Upgrade existing packages
chroot $imagedir apt-get -y upgrade | spin
[ $PIPESTATUS == 0 ] || die "apt-get upgrade failed!"
