#!/bin/bash
# Upgrade and cleanup packages installed by debootstrap

# Don't launch daemons when upgrading
cat << EOF > $imagedir/usr/sbin/policy-rc.d
#!/bin/sh
exit 101
EOF
chmod 755 $imagedir/usr/sbin/policy-rc.d

# Update the package cache
chroot $imagedir apt-get update | spin

# Fix broken dependencies, if any.
chroot $imagedir apt-get -f install -y

# Upgrade existing packages
chroot $imagedir apt-get -y upgrade | spin

# Purge all packages that are unused
chroot $imagedir apt-get autoremove --purge

# Erase downloaded archive files
chroot $imagedir apt-get clean

# Enable the daemons again and remove aptitude cache
rm -rf \
	$imagedir/usr/sbin/policy-rc.d \
	$imagedir/var/cache/apt/*.bin  \
	$imagedir/var/lib/apt/lists

# Recreate the partial directory
mkdir -p $imagedir/var/lib/apt/lists/partial
