#!/bin/bash
# Install packages

# Update the package cache
chroot $imagedir apt-get update

# Fix broken dependencies, if any.
chroot $imagedir apt-get -f install -y

# Upgrade existing packages
chroot $imagedir apt-get -y upgrade
