#!/bin/bash
# Disable normal grub 2 cfg files
chmod -x $imagedir/etc/grub.d/*

# Install the 40_custom file, which generates a nice menu.lst
script='40_custom'
cp "$scriptdir/grub.d/$script" "$imagedir/etc/grub.d/$script"
chmod 755 "$imagedir/etc/grub.d/$script"

# Update grub.cfg using the script
chroot $imagedir update-grub

# Alias grub.cfg as menu.lst
chroot $imagedir ln -s /boot/grub/grub.cfg /boot/grub/menu.lst
