#!/bin/bash
# Install kernel and kernel modules
[ $arch = 'i386' ] && module_package='linux-image-xen-686'
[ $arch = 'amd64' ] && module_package='linux-image-xen-amd64'

export DEBIAN_FRONTEND=noninteractive
chroot $imagedir apt-get install -y $module_package
unset DEBIAN_FRONTEND

# Xen expects a single tty1
/bin/rm -f $imagedir/etc/event.d/tty[2-6]
