#!/bin/bash
cat > $imagedir/etc/fstab <<EOF
/dev/xvda1 /     $filesystem    defaults 1 1
/dev/xvda3 swap  swap    defaults 0 0
none       /proc proc    defaults 0 0
none       /sys  sysfs   defaults 0 0
EOF
