#!/bin/bash
# Disable getty processes
# Login happens via SSH, and XEN needs to TTY
inittab="$imagedir/etc/inittab"
tty1='1:2345:respawn:/sbin/getty 38400 tty1'
ttyx=':23:respawn:/sbin/getty 38400 tty'
sed -i "s_^${tty1}_#${tty1}_" $inittab
sed -i "s_^2${ttyx}2_#2${ttyx}2_" $inittab
sed -i "s_^3${ttyx}3_#3${ttyx}3_" $inittab
sed -i "s_^4${ttyx}4_#4${ttyx}4_" $inittab
sed -i "s_^5${ttyx}5_#5${ttyx}5_" $inittab
sed -i "s_^6${ttyx}6_#6${ttyx}6_" $inittab
