#!/bin/bash
# Security
chroot $imagedir shadowconfig on
chroot $imagedir passwd -d root
sed -i -e 's/^#PasswordAuthentication yes/PasswordAuthentication no/' $imagedir/etc/ssh/sshd_config
cat <<'EOF' >>$imagedir/etc/ssh/sshd_config
UseDNS no
EOF
