#!/bin/bash
# Basic networking

# Delete the hostname file, we get it from the ec2 dhcp server
rm -f $imagedir/etc/hostname

# let the DHCP client manage /etc/resolv.conf
sed -i -e "s/^#*SET_DNS=.*/SET_DNS='yes'/" $imagedir/etc/default/dhcpcd
