#!/bin/bash
# Add ec2 startup scripts to the init_scripts list
init_scripts+=("$scriptdir/init.d/ec2-mkdir-tmp")
init_scripts+=("$scriptdir/init.d/ec2-ssh-host-key-gen")
init_scripts+=("$scriptdir/init.d/ec2-get-credentials")
if [ ! $no_run_user_data ]; then
	init_scripts+=("$scriptdir/init.d/ec2-run-user-data")
fi
