#!/bin/bash
# Cleanup after aptitude

# Purge all packages that are unused
chroot $imagedir apt-get autoremove --purge

# Erase downloaded archive files
chroot $imagedir apt-get clean

# Enable the daemons again and remove aptitude cache
rm -rf \
	$imagedir/usr/sbin/policy-rc.d \
	$imagedir/var/cache/apt/*.bin  \
	$imagedir/var/lib/apt/lists

# Recreate the partial directory
mkdir -p $imagedir/var/lib/apt/lists/partial
