#!/bin/bash
# Clean up the image

# Purge all packages that are unused
chroot $imagedir apt-get autoremove --purge

# Erase downloaded archive files
chroot $imagedir apt-get clean

# Enable the daemons again, remove temporary files, log files etc.
rm -rf \
	$imagedir/usr/sbin/policy-rc.d         \
	$imagedir/var/log/{bootstrap,dpkg}.log \
	$imagedir/var/cache/apt/*.bin          \
	$imagedir/var/lib/apt/lists            \
	$imagedir/tmp/*                        \
	$imagedir/root/.bash_history

# Recreate the partial directory
mkdir -p $imagedir/var/lib/apt/lists/partial
