#!/bin/bash
# Clean up the image

# Remove log files, temporary files and bash history
rm -rf \
	$imagedir/var/log/{bootstrap,dpkg}.log \
	$imagedir/tmp/*                        \
	$imagedir/root/.bash_history
