#!/bin/bash
# Unmount special devices

# We unmount from inside the image, otherwise the system won't boot
chroot $imagedir umount /dev/pts
chroot $imagedir umount /sys
chroot $imagedir umount /proc
umount $imagedir/dev

# No need to umount on errors any longer, but keep the trap used by
# Google Compute Engine builds if present.
trap "
declare -F cleanup_loopback_mount >/dev/null 2>&1 && cleanup_loopback_mount
" ERR EXIT

# Unmount the entire volume now

# cd out of the volume, otherwise we step on our own feet
cd $scriptdir

# Wait for the volume to idle, maybe the user is currently in it
while [ -n "`lsof $imagedir`" ]; do
	log "Waiting for volume to idle, before unmounting."
	sleep 5
done
