#!/bin/bash
case $region in
	eu-west-1)
		[ $arch = 'i386' ] && aki="aki-4deec439"
		[ $arch = 'amd64' ] && aki="aki-4feec43b"
	;;
	us-east-1)
		[ $arch = 'i386' ] && aki="aki-407d9529"
		[ $arch = 'amd64' ] && aki="aki-427d952b"
	;;
	us-west-1)
		[ $arch = 'i386' ] && aki="aki-99a0f1dc"
		[ $arch = 'amd64' ] && aki="aki-9ba0f1de"
	;;
	us-west-2)
		[ $arch = 'i386' ] && aki="aki-dce26fec"
		[ $arch = 'amd64' ] && aki="aki-ace26f9c"
	;;
	ap-northeast-1)
		[ $arch = 'i386' ] && aki="aki-d209a2d3"
		[ $arch = 'amd64' ] && aki="aki-d409a2d5"
	;;
	ap-southeast-1)
		[ $arch = 'i386' ] && aki="aki-13d5aa41"
		[ $arch = 'amd64' ] && aki="aki-11d5aa43"
	;;
	sa-east-1)
		[ $arch = 'i386' ] && aki="aki-863ce39b"
		[ $arch = 'amd64' ] && aki="aki-d63ce3cb"
	;;
	*)              die "$0: Unrecognized region: $region"
esac

ami_name="$distribution-$codename-$arch-$(date +%Y%m%d)"
echo "Registering the snapshot '$snapshot_id' as an AMI"
ami_id=`ec2-register \
	--name "$ami_name" --description "$description" \
	--architecture "$bundlearch" --kernel "$aki" \
	--snapshot "$snapshot_id" | awk '{print $2}'`
if [ -z "$ami_id" ]; then
	die \
		"Unable to register the snapshot as an AMI." \
		"You can do it manually with ec2-register" \
		"--name \"$ami_name\" --description \"$description\" " \
		"--architecture \"$bundlearch\" --kernel \"$aki\" --snapshot \"$snapshot_id\""
fi
echo "Your AMI has been created with the ID $ami_id"
