#!/bin/bash
# Register the snapshot as a new AMI

# Figure out which pvGrub kernel ID we need
case $region in
	eu-west-1)
		[ $arch = 'i386' ] && aki="aki-4deec439"
		[ $arch = 'amd64' ] && aki="aki-4feec43b"
	;;
	us-east-1)
		[ $arch = 'i386' ] && aki="aki-407d9529"
		[ $arch = 'amd64' ] && aki="aki-427d952b"
	;;
	us-west-1)
		[ $arch = 'i386' ] && aki="aki-99a0f1dc"
		[ $arch = 'amd64' ] && aki="aki-9ba0f1de"
	;;
	us-west-2)
		[ $arch = 'i386' ] && aki="aki-dce26fec"
		[ $arch = 'amd64' ] && aki="aki-ace26f9c"
	;;
	ap-northeast-1)
		[ $arch = 'i386' ] && aki="aki-d209a2d3"
		[ $arch = 'amd64' ] && aki="aki-d409a2d5"
	;;
	ap-southeast-1)
		[ $arch = 'i386' ] && aki="aki-13d5aa41"
		[ $arch = 'amd64' ] && aki="aki-11d5aa43"
	;;
	sa-east-1)
		[ $arch = 'i386' ] && aki="aki-863ce39b"
		[ $arch = 'amd64' ] && aki="aki-d63ce3cb"
	;;
	*) die "Unrecognized region:" "$region"
esac


[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

# The AMI has to start with "debian", otherwise we won't get a nice icon
ami_name="$distribution-$codename-$arch-$ami_name_suffix"
log "Registering the snapshot '$snapshot_id' as an AMI"
ami_id=`ec2-register \
	--name "$ami_name" --description "$description" \
	--architecture "$ami_arch" --kernel "$aki" \
	--block-device-mapping '/dev/sda2=ephemeral0' \
	--block-device-mapping '/dev/sda3=ephemeral1' \
	--block-device-mapping '/dev/sdb=ephemeral2' \
	--block-device-mapping '/dev/sdc=ephemeral3' \
	--block-device-mapping '/dev/sdd=ephemeral4' \
	--block-device-mapping '/dev/sde=ephemeral5' \
	--snapshot "$snapshot_id" | awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [ -z "$ami_id" ]; then
	die \
		"Unable to register the snapshot as an AMI." \
		"You can do it manually with:\nec2-register" \
		"--name '$ami_name' --description '$description' \\\\" \
		"--architecture '$ami_arch' --kernel '$aki' \\\\" \
		"--block-device-mapping '/dev/sda2=ephemeral0' \\\\" \
		"--block-device-mapping '/dev/sda3=ephemeral1' \\\\" \
		"--block-device-mapping '/dev/sdb=ephemeral2' \\\\" \
		"--block-device-mapping '/dev/sdc=ephemeral3' \\\\" \
		"--block-device-mapping '/dev/sdd=ephemeral4' \\\\" \
		"--block-device-mapping '/dev/sde=ephemeral5' \\\\" \
		"--snapshot '$snapshot_id'"
fi
log "Your AMI has been created with the ID $ami_id"
