#!/bin/bash
device='/dev/sdf'
device_path='/dev/xvdf'
filesystem='xfs'

[ -n "`df | grep $device_path`" ] && die "Something is already attached to $device_path."

metadata_url='http://169.254.169.254/latest/meta-data'
instance_id=`curl --silent $metadata_url/instance-id`
availability_zone=`curl --silent $metadata_url/placement/availability-zone`

if [ -z "$instance_id" ]; then
	die \
		"Unable to fetch the instance id of this machine." \
		"This script must be running on ec2 in order to mount EBS volumes."
fi
[ -z "$availability_zone" ] && die "Unable to fetch the availability zone of this machine."

if [ -z "$volume_id" ]; then
	echo "No volume id specified, creating a volume now."
	volume_id=`ec2-create-volume --size 1 --availability-zone "$availability_zone" | awk '{print $2}'`
	[ -z "$volume_id" ] && die "Unable to create volume."
else
	echo "Checking the status of the specified volume."
	volume_status=`ec2-describe-volumes | grep "VOLUME	$volume_id" | awk '{print $(NF-1)}'`
	if [ "$volume_status" != 'available' ]; then
		die \
			"Please detach the volume $volume_id. Even if it is this instance it is" \
			"attached to.
			You can of course also simply mount the volume, specify the " \
			"mountpoint and skip this procedure entirely." \
			"Otherwise detach with 'ec2-detach-volume $volume_id'."
	fi
fi
echo "Attaching volume with the id $volume_id"
attachment_status=`ec2-attach-volume "$volume_id" --instance "$instance_id" --device "$device" | awk '{print $5}'`
while [ "$attachment_status" != "attached" ]
do
	echo "Waiting for volume to finish attaching"
	sleep 5
	attachment_status=`ec2-describe-volumes | grep "ATTACHMENT	$volume_id" | awk '{print $5}'`
done
echo "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path
mount $device_path $builddir
echo "The EBS volume has been formatted and mounted"

case $filesystem in
	xfs)  packages="$packages xfsprogs" ;;
	ext2) ;;
	ext3) ;;
	ext4) ;;
	*)    echo "Tools for $filesystem were not added, the corresponding package is unknown" >&2;;
esac
