#!/bin/bash
device='/dev/sdf'
device_path='/dev/xvdf'
filesystem='xfs'

if [ -n "`df | grep $device_path`" ]; then
	echo >&2 "Something is already attached to $device_path."
	exit
fi

instance_id=`curl --silent http://169.254.169.254/latest/meta-data/instance-id`
availability_zone=`curl --silent http://169.254.169.254/latest/meta-data/placement/availability-zone`
if [ -z "$volume_id" ]; then
	echo "No volume id specified, creating a volume now."
	volume_id=`ec2-create-volume --size 1 --availability-zone "$availability_zone" | awk '{print $2}'`
else
	echo "Checking the status of the specified volume."
	volume_status=`ec2-describe-volumes | grep "VOLUME	$volume_id" | awk '{print $(NF-1)}'`
	if [ "$volume_status" != 'available' ]; then
		echo "Please detach the volume $volume_id. Even if it is this instance it is attached to." >&2
		echo "You can of course also simply mount the volume specify the mountpoint and skip this procedure entirely." >&2
		echo "Do this with ec2-detach-volume $volume_id"
		exit
	fi
fi
echo "Attaching volume with the id $volume_id"
attachment_status=`ec2-attach-volume "$volume_id" --instance "$instance_id" --device "$device" | awk '{print $5}'`
while [ "$attachment_status" != "attached" ]
do
	echo "Waiting for volume to finish attaching"
	sleep 5
	attachment_status=`ec2-describe-volumes | grep "ATTACHMENT	$volume_id" | awk '{print $5}'`
done
echo "Formatting the device $device_path with $filesystem"
mkfs.$filesystem $device_path
mount $device_path $builddir
echo "The EBS volume has been formatted and mounted"

case $filesystem in
  xfs)  packages="$packages xfsprogs" ;;
  ext2) ;;
  ext3) ;;
  ext4) ;;
  *)    echo "Tools for $filesystem were not added, the corresponding package is unknown" >&2;;
esac
