#!/bin/bash
fstab=$builddir/etc/fstab
mount_entry=`mount | grep $builddir`
if [ -z "$mount_entry" ]; then
	echo >&2 "Could not determine $builddir file system type for $fstab"
	echo >&2 "You'll need to manually create $fstab"
	exit 1
fi

type=`echo $mount_entry | cut -f5 -d' '`
cat >$fstab <<EOF
/dev/xvda1 /     $type    defaults 1 1
/dev/xvda3 swap  swap    defaults 0 0
none      /proc proc    defaults 0 0
none      /sys  sysfs   defaults 0 0
EOF

if [ $bsarch = 'amd64' ]; then
	aki="aki-4feec43b"
elif [ $bsarch = 'i386' ]; then
	aki="aki-4deec439"
fi

echo "Creating snapshot of the EBS volume"
snapshot=`ec2-create-snapshot $volume_id`
snapshot_id=`echo $snapshot | awk '{print $2}'`
snapshot_status=`echo $snapshot | awk '{print $4}'`
while [ "$snapshot_status" != "completed" ]
do
	echo "Waiting for snapshot to be completed"
	sleep 5
	snapshot_status=`ec2-describe-snapshots | grep $snapshot_id | awk '{print $4}'`
done
ami_name="$distribution-$codename-$bsarch-$(date +%Y%m%d)"
echo "Registering the snapshot '$snapshot_id' as an AMI"
ami_id=`ec2-register --architecture "$bundlearch" --name "$ami_name" --description "$description" --kernel "$aki" --snapshot "$snapshot_id" | awk '{print $2}'`

echo "Your AMI has been created with the ID $ami_id"
