#!/bin/bash
# Export build parameters so they are available in external scripts
export regions_aki distribution description release codename timezone locale charmap size \
  scripts packages modules desktop builddir imagedir bundlearch \
  AWS_USER_ID AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY EC2_PRIVATE_KEY EC2_CERT

if [ -z "$ebs" ]
then
  export tag bucket prefix
fi

# Invoke external scripts/commands if requested
export DEBIAN_FRONTEND=noninteractive
for script in "${scripts[@]}"; do
  cd "$originaldir"
  status=
  if [ -x "$script" ]; then
    "$script"
    status=$?
  elif [ -f "$script" ]; then
    /bin/bash "$script"
    status=$?
  else
    eval $script
  fi

  if [ -n "$status" -a "$status" -ne 0 ]; then
    echo "Execution of '$script' failed with status $status" >&2
    exit $status
  fi
done
unset DEBIAN_FRONTEND
cd $builddir
