#!/bin/bash
# Install packages on the builing system to make the rest of this script run smoothly.
apt-get install -y bzip2 binutils unzip debootstrap rsync ruby openssl curl ca-certificates libopenssl-ruby default-jre-headless

export JAVA_HOME=`update-java-alternatives --list | cut -f 3 -d ' ' | tail -n 1`