#!/bin/bash
# Install kernel and kernel modules
if [ -n "$modules" ]; then
	# To build kernel modules yourself, see:
	# http://alestic.com/2008/05/kernel-modules-2-6-21
	for module in $modules; do
		curl -s $module | tar xjC $imagedir
	done
	chown -R root.root $imagedir/lib/modules
else
	if [ $bsarch = 'amd64' ]; then
		module_package='linux-image-xen-amd64'
	elif [ $bsarch = 'i386' ]; then
		module_package='linux-image-xen-686'
	else
		echo >&2 "$0: Unrecognized --arch $bsarch"
		exit 1
	fi
	export DEBIAN_FRONTEND=noninteractive
	chroot $imagedir apt-get install -y $module_package
	unset DEBIAN_FRONTEND
fi

# This kernel module has historically been loaded; keeping the tradition.
# Also, xfs is the default fs of this tool now.
# Could come in handy when you are, you know... booting.
echo "xfs" >> $imagedir/etc/modules

for module_version in $(cd $imagedir/lib/modules; ls); do
	chroot $imagedir depmod -a $module_version
done
