#!/bin/bash
if [ -z "$ebs" ]; then
	mkdir -p $builddir
	cd $builddir
	imagedir=$builddir/$distribution
	mkdir -p $imagedir
else
	if [ ! -d "$builddir" ]; then
		mkdir -p $builddir
		source $scriptdir/tasks/create-volume
	elif [ -z "`mount | grep "$builddir"`" ]; then
		source $scriptdir/tasks/create-volume
	else
		echo "Using the volume already mounted on $builddir"
		if [ -z "$volume_id" ]; then
			die \
				"You must specify the volume ID when you want to mount it yourself." \
				"Otherwise creating the snapshot later on will not be possible."
		fi
	fi
	imagedir=$builddir
fi
