#!/bin/bash
# Mostly copied from the create-volume task

# Get a random device letter, we will hang forever if we try to attach a volume to an already mapped device.
device_letter=`cat /dev/urandom| tr -dc 'f-p'|head -c 1`
while [ -b "/dev/xvd$device_letter" ]; do
	device_letter=`cat /dev/urandom| tr -dc 'f-p'|head -c 1`
done
device_path="/dev/xvd$device_letter"

logn "Reattaching the bootstrapped volume"
euca-attach-volume --instance "$instance_id" --device "/dev/sd$device_letter" "$volume_id"
# Wait until the volume is attached
dotdot "euca-describe-volumes $volume_id | grep 'ATTACHMENT'"

# Recreate the imagedir, it was delete in the unmount task
log "Creating mount location ${imagedir}"
mkdir -p $imagedir

mount $device_path $imagedir
log "The volume has been mounted at $imagedir"

log "Run the following commands to unmount and remove the volume:"
logplain \
	"export EC2_URL=https://ec2.$region.amazonaws.com" \
	"umount $imagedir" \
	"rm -rf $imagedir" \
	"euca-detach-volume $volume_id" \
	"euca-delete-volume $volume_id"
