#!/bin/bash
# Mostly copied from the create-volume task

# Get a random device letter, we will hang forever if we try to attach a volume to an already mapped device.
for device_letter in {f..z}; do
	device_path="/dev/xvd$device_letter"
	[ ! -b $device_path ] && break
done
[ -b $device_path ] && die "No free device letters found (tried sdf to sdz)!"

logn "Reattaching the bootstrapped volume"
euca-attach-volume --instance "$instance_id" --device "/dev/sd$device_letter" "$volume_id"
# Wait until the volume is attached
dotdot "test -b $device_path && echo attached"

# Recreate the imagedir, it was delete in the unmount task
log "Creating mount location ${imagedir}"
mkdir -p $imagedir

mount $device_path $imagedir
log "The volume has been mounted at $imagedir"

log "Run the following commands to unmount and remove the volume:"
logplain \
	"export EC2_URL=https://ec2.$region.amazonaws.com" \
	"umount $imagedir" \
	"rm -rf $imagedir" \
	"euca-detach-volume $volume_id" \
	"euca-delete-volume $volume_id"
