#!/bin/bash
admin_username='admin'

# Create the user
chroot $imagedir useradd --create-home --shell /bin/bash $admin_username

# Allow ec2-user to use sudo without a password
cat > $imagedir/etc/sudoers.d/99_admin <<EOF
$admin_username ALL=(ALL) NOPASSWD:ALL
EOF
chmod 440 $imagedir/etc/sudoers.d/99_admin

# ec2-get-credentials should add the pubkey to the new user account and not root
sed -i "s/^username='root'/username='$admin_username'/" $imagedir/etc/init.d/ec2-get-credentials

# Disallow root login
sed -i "s/^PermitRootLogin yes/PermitRootLogin no/" $imagedir/etc/ssh/sshd_config
