#!/bin/bash
insert_task_after $TASK_PACKAGES \
	$plugindir/unattended-upgrades-tasks/add-unattended-upgrades-package
insert_task_before $TASK_APTSOURCES \
	$plugindir/unattended-upgrades-tasks/create-02periodic
