#!/bin/bash
# Register the uploaded bundle as a new AMI

# Figure out which pvGrub kernel ID we need
case $region in
        us-east-1)
                [ $arch = 'amd64' ] && aki="aki-88aa75e1"
                [ $arch = 'i386' ] && aki="aki-b6aa75df"
        ;;
        us-west-1)
                [ $arch = 'amd64' ] && aki="aki-f77e26b2"
                [ $arch = 'i386' ] && aki="aki-f57e26b0"
        ;;
        us-west-2)
                [ $arch = 'amd64' ] && aki="aki-fc37bacc"
                [ $arch = 'i386' ] && aki="aki-fa37baca"
        ;;
        eu-west-1)
                [ $arch = 'amd64' ] && aki="aki-71665e05"
                [ $arch = 'i386' ] && aki="aki-75665e01"
        ;;
        ap-southeast-1)
                [ $arch = 'amd64' ] && aki="aki-fe1354ac"
                [ $arch = 'i386' ] && aki="aki-f81354aa"
        ;;
        ap-southeast-2)
                [ $arch = 'amd64' ] && aki="aki-31990e0b"
                [ $arch = 'i386' ] && aki="aki-33990e09"
        ;;
        ap-northeast-1)
                [ $arch = 'amd64' ] && aki="aki-44992845"
                [ $arch = 'i386' ] && aki="aki-42992843"
        ;;
        sa-east-1)
                [ $arch = 'amd64' ] && aki="aki-c48f51d9"
                [ $arch = 'i386' ] && aki="aki-ca8f51d7"
        ;;
        us-gov-west-1)
                [ $arch = 'amd64' ] && aki="aki-79a4c05a"
                [ $arch = 'i386' ] && aki="aki-7ba4c058"
        ;;
        *) die "Unrecognized region:" "$region"
esac


[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

ami_name="$distribution-$codename-$arch-$name_suffix"
log "Registering an AMI"
ami_id=`euca-register "${bucketname}/${volume_id}.manifest.xml" \
        --name "$ami_name" --description "$description" \
        --architecture "$ami_arch" --kernel "$aki" \
        | awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
	die "Unable to register an AMI."
#        die \
#                "Unable to register an AMI." \
#                "You can do it manually with:" \
#                "`which euca-register` \\\\" \
#                "--name '$ami_name' --description '$description' \\\\" \
#                "--architecture '$ami_arch' --kernel '$aki' \\\\" \
#                "--snapshot '$snapshot_id:$volume_size:true:standard'"
fi
log "Your AMI has been created with the ID '$ami_id'"

