#!/bin/bash
function remove_init_script {
	local new_init_scripts=()
	for init_script in ${init_scripts[*]}; do
		if [ "$init_script" != "$1" ]; then
			new_init_scripts+=($init_script)
	fi
	done
	init_scripts=("${new_init_scripts[@]}")
}
remove_init_script "$scriptdir/init.d/ec2-run-user-data"
