#!/usr/bin/python
# -*- coding: utf-8 -*-

# Software License Agreement (BSD License)
#
# Copyright (c) 2009, Eucalyptus Systems, Inc.
# All rights reserved.
#
# Redistribution and use of this software in source and binary forms, with or
# without modification, are permitted provided that the following conditions
# are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other
#   materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Neil Soman neil@eucalyptus.com

import getopt
import sys
import os
from euca2ools import Euca2ool, SnapshotValidationError, Util, \
    ConnectionFailed

usage_string = \
    """
Modify attributes for a snapshot.

euca-modify-snapshot-attribute [-c, --create-volume-permission]
[-a, --add entity ] [-r, --remove entity]
[-h, --help] [--version] [--debug] snapshot_id

REQUIRED PARAMETERS

snapshot_id      Unique identifier for the snapshot that you want to modify the attributes for.

OPTIONAL PARAMETERS

-c, --create-volume-permission   Create volume permissions.

-a, --add      Entity (typically, user id) to add.

-r, --remove      Entity (typically, user id) to remove.
"""


def usage(status=1):
    print usage_string
    Util().usage(compat=True)
    sys.exit(status)


def version():
    print Util().version()
    sys.exit()


def main():
    euca = None
    try:
        euca = Euca2ool('c:a:r:', ['create-volume-permission', 'add=', 'remove='], compat=True)
    except Exception, e:
        print e
        usage()

    snapshot_id = None
    entity = None
    snapshot_attribute = None
    operation_type = None
    user_ids = None
    groups = None

    for (name, value) in euca.opts:
        if name in ('-l', '--create-volume-permission'):
            if not snapshot_attribute:
                snapshot_attribute = 'createVolumePermission'
        elif name in ('-a', '--add'):
            entity = value
            operation_type = 'add'
        elif name in ('-r', '--remove'):
            entity = value
            operation_type = 'remove'
        elif name in ('-h', '--help'):
            usage(0)
        elif name == '--version':
            version()

    for arg in euca.args:
        snapshot_id = arg
        break

    if snapshot_attribute == 'createVolumePermission':
        if entity == 'all':
            groups = [entity]
        else:
            user_ids = [entity]

    if snapshot_id and snapshot_attribute:
        try:
            euca.validate_snapshot_id(snapshot_id)
        except SnapshotValidationError:
            print 'Invalid snapshot id'
            sys.exit(1)

        try:
            euca_conn = euca.make_connection()
        except ConnectionFailed, e:
            print e.message
            sys.exit(1)
        try:
            return_code = euca_conn.modify_snapshot_attribute(
                snapshot_id=snapshot_id,
                attribute=snapshot_attribute,
                operation=operation_type,
                user_ids=user_ids,
                groups=groups,
                )
        except Exception, ex:
            euca.display_error_and_exit('%s' % ex)

        if return_code:
            print 'SNAPSHOT\t%s' % snapshot_id
    else:
        if not snapshot_id:
            print 'snapshot_id must be specified'
        if not snapshot_attribute:
            print '-c must be specified'
        usage()


if __name__ == '__main__':
    main()
