#!/bin/bash
### BEGIN INIT INFO
# Provides:       change-root-uuid
# Required-Start: 
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  2 3 4 5
# Default-Stop:   
# Description:    Changes the UUID of the root volume
### END INIT INFO

prog=$(basename $0)
logger="logger -t $prog"

device_path="/dev/xvda1"

filesystem=`blkid | grep $device_path | sed 's#\(.*\):.*TYPE="\(.*\)".*#\2#'`

case $filesystem in
	ext2) tune2fs -U random $device_path ;;
	ext3) tune2fs -U random $device_path ;;
	ext4) tune2fs -U random $device_path ;;
	*)    $logger "The filesystem $filesystem was not recognized. Unable to change its UUID." ;;
esac

# Disable this script, it may only run once
insserv -r $0
