#!/bin/sh
### BEGIN INIT INFO
# Provides:       ec2-ssh-host-key-gen
# Required-Start: $network
# Required-Stop:  
# Should-Start:   
# Should-Stop:    
# Default-Start:  S
# Default-Stop:   
# Description:    Generate ssh host keys on first boot
### END INIT INFO
#
# ec2-ssh-host-key-gen - Generate ssh host keys on first boot
#
# Generates the ssh host keys on every new instance
#

prog=$(basename $0)

rsa_key="/etc/ssh/ssh_host_rsa_key"
dsa_key="/etc/ssh/ssh_host_dsa_key"

# Exit if we have already run on this instance (e.g., previous boot).
if [ -f $rsa_key ]; then
	exit
fi

# Generate the ssh host keys
ssh-keygen -f $rsa_key -t rsa -C 'host' -N ''
ssh-keygen -f $dsa_key -t dsa -C 'host' -N ''

# Output the public keys to the console
# This allows user to get host keys securely through console log
echo "-----BEGIN SSH HOST KEY FINGERPRINTS-----"  | logger -st "ec2" 
ssh-keygen -l -f $rsa_key.pub    | logger -st "ec2"
ssh-keygen -l -f $dsa_key.pub    | logger -st "ec2"
echo "-----END SSH HOST KEY FINGERPRINTS-----"    | logger -st "ec2" 
